/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "twitter_constants.h"

namespace twitter {

const twitterConstants g_twitter_constants;

twitterConstants::twitterConstants() {
}

} // namespace

