/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef twitter_CONSTANTS_H
#define twitter_CONSTANTS_H

#include "twitter_types.h"

namespace twitter {

class twitterConstants {
 public:
  twitterConstants();

};

extern const twitterConstants g_twitter_constants;

} // namespace

#endif
