/**
 * Autogenerated by Thrift Compiler (0.11.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef twitter_TYPES_H
#define twitter_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/stdcxx.h>


namespace twitter {

class Timestamp;

class Tweet_;

class User_;

class File_;

class Tweet;

typedef struct _Timestamp__isset {
  _Timestamp__isset() : service_name(false), function_name(false), timestamp(false) {}
  bool service_name :1;
  bool function_name :1;
  bool timestamp :1;
} _Timestamp__isset;

class Timestamp : public virtual ::apache::thrift::TBase {
 public:

  Timestamp(const Timestamp&);
  Timestamp& operator=(const Timestamp&);
  Timestamp() : service_name(), function_name(), timestamp(0) {
  }

  virtual ~Timestamp() throw();
  std::string service_name;
  std::string function_name;
  int64_t timestamp;

  _Timestamp__isset __isset;

  void __set_service_name(const std::string& val);

  void __set_function_name(const std::string& val);

  void __set_timestamp(const int64_t val);

  bool operator == (const Timestamp & rhs) const
  {
    if (!(service_name == rhs.service_name))
      return false;
    if (!(function_name == rhs.function_name))
      return false;
    if (!(timestamp == rhs.timestamp))
      return false;
    return true;
  }
  bool operator != (const Timestamp &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Timestamp & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Timestamp &a, Timestamp &b);

std::ostream& operator<<(std::ostream& out, const Timestamp& obj);

typedef struct _Tweet___isset {
  _Tweet___isset() : tweet_id(false), user_id(false), file_id(false), text(false), timestamps(false) {}
  bool tweet_id :1;
  bool user_id :1;
  bool file_id :1;
  bool text :1;
  bool timestamps :1;
} _Tweet___isset;

class Tweet_ : public virtual ::apache::thrift::TBase {
 public:

  Tweet_(const Tweet_&);
  Tweet_& operator=(const Tweet_&);
  Tweet_() : tweet_id(), user_id(), file_id(), text() {
  }

  virtual ~Tweet_() throw();
  std::string tweet_id;
  std::string user_id;
  std::string file_id;
  std::string text;
  std::vector<Timestamp>  timestamps;

  _Tweet___isset __isset;

  void __set_tweet_id(const std::string& val);

  void __set_user_id(const std::string& val);

  void __set_file_id(const std::string& val);

  void __set_text(const std::string& val);

  void __set_timestamps(const std::vector<Timestamp> & val);

  bool operator == (const Tweet_ & rhs) const
  {
    if (!(tweet_id == rhs.tweet_id))
      return false;
    if (!(user_id == rhs.user_id))
      return false;
    if (!(file_id == rhs.file_id))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(timestamps == rhs.timestamps))
      return false;
    return true;
  }
  bool operator != (const Tweet_ &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Tweet_ & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Tweet_ &a, Tweet_ &b);

std::ostream& operator<<(std::ostream& out, const Tweet_& obj);

typedef struct _User___isset {
  _User___isset() : user_id(false), username(false), homepage(false), timestamps(false) {}
  bool user_id :1;
  bool username :1;
  bool homepage :1;
  bool timestamps :1;
} _User___isset;

class User_ : public virtual ::apache::thrift::TBase {
 public:

  User_(const User_&);
  User_& operator=(const User_&);
  User_() : user_id(), username(), homepage() {
  }

  virtual ~User_() throw();
  std::string user_id;
  std::string username;
  std::string homepage;
  std::vector<Timestamp>  timestamps;

  _User___isset __isset;

  void __set_user_id(const std::string& val);

  void __set_username(const std::string& val);

  void __set_homepage(const std::string& val);

  void __set_timestamps(const std::vector<Timestamp> & val);

  bool operator == (const User_ & rhs) const
  {
    if (!(user_id == rhs.user_id))
      return false;
    if (!(username == rhs.username))
      return false;
    if (!(homepage == rhs.homepage))
      return false;
    if (!(timestamps == rhs.timestamps))
      return false;
    return true;
  }
  bool operator != (const User_ &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const User_ & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(User_ &a, User_ &b);

std::ostream& operator<<(std::ostream& out, const User_& obj);

typedef struct _File___isset {
  _File___isset() : file_id(false), content(false), timestamps(false) {}
  bool file_id :1;
  bool content :1;
  bool timestamps :1;
} _File___isset;

class File_ : public virtual ::apache::thrift::TBase {
 public:

  File_(const File_&);
  File_& operator=(const File_&);
  File_() : file_id(), content() {
  }

  virtual ~File_() throw();
  std::string file_id;
  std::string content;
  std::vector<Timestamp>  timestamps;

  _File___isset __isset;

  void __set_file_id(const std::string& val);

  void __set_content(const std::string& val);

  void __set_timestamps(const std::vector<Timestamp> & val);

  bool operator == (const File_ & rhs) const
  {
    if (!(file_id == rhs.file_id))
      return false;
    if (!(content == rhs.content))
      return false;
    if (!(timestamps == rhs.timestamps))
      return false;
    return true;
  }
  bool operator != (const File_ &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const File_ & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(File_ &a, File_ &b);

std::ostream& operator<<(std::ostream& out, const File_& obj);

typedef struct _Tweet__isset {
  _Tweet__isset() : tweet_id(false), user(false), text(false), file(false), timestamps(false) {}
  bool tweet_id :1;
  bool user :1;
  bool text :1;
  bool file :1;
  bool timestamps :1;
} _Tweet__isset;

class Tweet : public virtual ::apache::thrift::TBase {
 public:

  Tweet(const Tweet&);
  Tweet& operator=(const Tweet&);
  Tweet() : tweet_id(), text() {
  }

  virtual ~Tweet() throw();
  std::string tweet_id;
  User_ user;
  std::string text;
  File_ file;
  std::vector<Timestamp>  timestamps;

  _Tweet__isset __isset;

  void __set_tweet_id(const std::string& val);

  void __set_user(const User_& val);

  void __set_text(const std::string& val);

  void __set_file(const File_& val);

  void __set_timestamps(const std::vector<Timestamp> & val);

  bool operator == (const Tweet & rhs) const
  {
    if (!(tweet_id == rhs.tweet_id))
      return false;
    if (!(user == rhs.user))
      return false;
    if (!(text == rhs.text))
      return false;
    if (!(file == rhs.file))
      return false;
    if (!(timestamps == rhs.timestamps))
      return false;
    return true;
  }
  bool operator != (const Tweet &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Tweet & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  virtual void printTo(std::ostream& out) const;
};

void swap(Tweet &a, Tweet &b);

std::ostream& operator<<(std::ostream& out, const Tweet& obj);

} // namespace

#endif
